# Generated by Django 4.2.13 on 2026-06-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sync_image_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='True after the user clicks the email verification link sent at registration.'),
        ),
    ]
