# Generated by Django 4.2.13 on 2026-06-02 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('site_title', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('business_type', models.CharField(choices=[('market', 'Market / General Shop'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics Store'), ('clothing', 'Clothing Store'), ('organic', 'Organic Market'), ('restaurant', 'Restaurant / Café'), ('hotel', 'Hotel / Guesthouse'), ('bar', 'Bar / Night Club'), ('delivery_kitchen', 'Food Delivery Kitchen'), ('bakery', 'Bakery'), ('car_rental', 'Car Rental'), ('property_rental', 'Property Rental'), ('equipment_rental', 'Equipment Rental'), ('boat_rental', 'Boat Rental'), ('barbershop', 'Barbershop / Hair Salon'), ('spa', 'Spa & Wellness'), ('gym', 'Gym / Fitness Studio'), ('clinic', 'Clinic / Dental'), ('tattoo', 'Tattoo Studio'), ('auto_repair', 'Auto Repair'), ('cleaning', 'Cleaning Service'), ('lawyer', 'Lawyer / Notary'), ('accounting', 'Accounting Firm'), ('event_agency', 'Event Agency'), ('language_school', 'Language School'), ('tutoring', 'Tutoring'), ('driving_school', 'Driving School'), ('coding_bootcamp', 'Coding Bootcamp')], default='restaurant', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7)),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Albania', max_length=100)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'key')},
            },
        ),
    ]
