# Generated by Django 4.2.13 on 2026-06-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
