# Generated by Django 4.2.13 on 2026-06-21 14:49

import bizal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenantlocation_id_alter_tenantreferral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/', validators=[bizal.validators.validate_image_type]),
        ),
    ]
