# Generated by Django 4.2.13 on 2026-06-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_sync_image_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='reply_from_email',
            field=models.EmailField(blank=True, help_text='Optional custom reply-from address for outgoing emails (e.g. info@mybusiness.al). Falls back to platform DEFAULT_FROM_EMAIL if blank.', max_length=254),
        ),
    ]
