# Generated by Django 4.2.13 on 2026-06-24 00:00
#
# Audit fix M-1: primary_color/accent_color had no format validation,
# allowing values that break out of the inline CSS <style> block they're
# interpolated into in invoice_pdf() (see billing/views.py). This syncs the
# new validate_hex_color validator (bizal/validators.py) onto both fields.
# Like 0008_sync_image_validators, this is a state-only AlterField — CharField
# validators are enforced in Python (forms/serializers/full_clean()), not at
# the database level, so no actual column type or constraint changes.

import bizal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_add_reply_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#2563EB', max_length=7, validators=[bizal.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='accent_color',
            field=models.CharField(default='#F59E0B', max_length=7, validators=[bizal.validators.validate_hex_color]),
        ),
    ]
