# Generated by Django 4.2.13 on 2026-07-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_sync_hex_color_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialTenant',
            fields=[
            ],
            options={
                'verbose_name': 'Trial tenant',
                'verbose_name_plural': 'Trial dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenants.tenant',),
        ),
    ]
