# Generated by Django 4.2.13 on 2026-07-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_trialtenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='border_radius',
            field=models.CharField(choices=[('2px', 'Të mprehta'), ('8px', 'Të buta (parazgjedhje)'), ('16px', 'Të rrumbullakosura'), ('28px', 'Pilulë')], default='8px', max_length=6),
        ),
        migrations.AddField(
            model_name='tenant',
            name='font_body',
            field=models.CharField(choices=[('Cormorant Garamond', 'Cormorant Garamond (parazgjedhje, elegante)'), ('DM Sans', 'DM Sans (parazgjedhje, neutrale)'), ('Inter', 'Inter (e pastër, moderne)'), ('Poppins', 'Poppins (e rrumbullakosur, miqësore)'), ('Playfair Display', 'Playfair Display (luksoze, editoriale)'), ('Merriweather', 'Merriweather (klasike, serif)'), ('Space Grotesk', 'Space Grotesk (moderne, teknike)'), ('Nunito', 'Nunito (e butë, e afërt)')], default='DM Sans', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='font_heading',
            field=models.CharField(choices=[('Cormorant Garamond', 'Cormorant Garamond (parazgjedhje, elegante)'), ('DM Sans', 'DM Sans (parazgjedhje, neutrale)'), ('Inter', 'Inter (e pastër, moderne)'), ('Poppins', 'Poppins (e rrumbullakosur, miqësore)'), ('Playfair Display', 'Playfair Display (luksoze, editoriale)'), ('Merriweather', 'Merriweather (klasike, serif)'), ('Space Grotesk', 'Space Grotesk (moderne, teknike)'), ('Nunito', 'Nunito (e butë, e afërt)')], default='Cormorant Garamond', max_length=50),
        ),
    ]
