# Generated by Django 4.2.13 on 2026-07-01 09:10
#
# Adds background_color/text_color so the tenant theme picker (font_heading/
# font_body/border_radius, added in 0012) can also control the storefront's
# page background and body text color. Defaults ('#FAFAF8' / '#111111')
# MUST match brand.css's --parchment/--ink fallbacks — see the comment on
# these fields in models.py.

import bizal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_border_radius_tenant_font_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='background_color',
            field=models.CharField(default='#FAFAF8', max_length=7, validators=[bizal.validators.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='text_color',
            field=models.CharField(default='#111111', max_length=7, validators=[bizal.validators.validate_hex_color]),
        ),
    ]
