# Generated by Django 4.2.13 on 2026-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_background_color_tenant_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='nav_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
