# Generated by Django 4.2.13 on 2026-07-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_nav_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(choices=[('ALL', 'Lek Shqiptar (ALL)'), ('EUR', 'Euro (EUR)'), ('USD', 'US Dollar (USD)')], default='ALL', max_length=3),
        ),
    ]
