# Generated by Django 4.2.13 on 2026-07-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accepts_online_payments',
            field=models.BooleanField(default=False),
        ),
    ]
