# Generated by Django 4.2.13 on 2026-09-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_main_sentinel_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accepts_cash_payments',
            field=models.BooleanField(default=True),
        ),
    ]