# Generated by Django 4.2.13 on 2026-08-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_reminder_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (Card)'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='online', max_length=20),
        ),
    ]