# Generated by Django 4.2.13 on 2026-06-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_new', 'New Appointment'), ('order_placed', 'Order Placed'), ('payment_success', 'Payment Successful'), ('subscription_expiring', 'Subscription Expiring'), ('new_review', 'New Review'), ('new_contact', 'New Contact Message'), ('info', 'Info')], max_length=50),
        ),
    ]
