# BizAL — convenience targets.
#
# `lock` / `lock-check` added as part of the requirements.txt audit fix:
# requirements.txt is a generated lockfile (full transitive pin closure),
# requirements.in is the hand-edited source of direct dependencies. Never
# edit requirements.txt by hand — run `make lock` after changing
# requirements.in, and commit the regenerated requirements.txt alongside it.

# lock-check's recipe uses <(...) process substitution, which /bin/sh
# (dash on Ubuntu, including GitHub Actions runners) doesn't support.
SHELL := /bin/bash

.PHONY: lock lock-check loadtest

# Regenerate backend/requirements.txt from backend/requirements.in.
# Requires network access to PyPI (this target cannot run in a
# network-isolated sandbox — see backend/requirements.txt header).
# requirements-dev.txt needs no separate lock step: it layers on top of
# requirements.txt via `-r requirements.txt` and pins only its own
# additional direct packages (coverage/flower/pytest), so it is already
# fully pinned by hand without a transitive closure of its own.
lock:
	cd backend && pip install -q pip-tools && \
	pip-compile requirements.in --output-file requirements.txt --strip-extras

# CI target: fail the build if requirements.in changed without regenerating
# requirements.txt. Compiles into a scratch copy and diffs against the
# committed lockfile rather than overwriting it in place.
#
# Only the dependency-pin body is diffed — the leading "# This file is
# autogenerated..." comment block is stripped from both sides first. That
# header records the exact pip-compile invocation (--output-file value,
# and apparently sometimes flags like --no-index that weren't even passed
# on the command line — a known pip-tools/click quirk where the recorded
# command can drift across pip-tools/click/environment versions). None of
# that is meaningful lockfile content, and comparing it makes the check
# fail on cosmetic differences instead of real drift between
# requirements.in and requirements.txt. sed prints from the first line
# that starts with a package name (a letter in column 1) onward, which
# skips the header regardless of how many lines it spans.
lock-check:
	rm -rf /tmp/lock-check && mkdir -p /tmp/lock-check && \
	cp backend/requirements.in /tmp/lock-check/requirements.in && \
	pip install -q pip-tools && \
	cd /tmp/lock-check && pip-compile requirements.in --output-file requirements.txt --strip-extras && cd - >/dev/null && \
	diff -u <(sed -n '/^[a-zA-Z]/,$$p' backend/requirements.txt) <(sed -n '/^[a-zA-Z]/,$$p' /tmp/lock-check/requirements.txt) && \
	echo "OK: requirements.txt is in sync with requirements.in"

# Headless load test against a locally-running server (see backend/loadtest/
# README.md for the full explanation and how to interpret results). Assumes
# `python manage.py runserver` is already up on :8000 and the DB is seeded
# (`python backend/seed.py`) — this target does not start the server itself
# so it can equally be pointed at a docker-compose or staging host by
# overriding HOST, e.g. `make loadtest HOST=https://staging.bizal.al`.
HOST ?= http://localhost:8000
USERS ?= 50
SPAWN_RATE ?= 10
RUN_TIME ?= 60s

loadtest:
	cd backend && locust -f loadtest/locustfile.py --host=$(HOST) \
	--headless -u $(USERS) -r $(SPAWN_RATE) --run-time $(RUN_TIME) \
	--csv=loadtest/results/run_$$(date +%Y%m%d_%H%M%S)