# Generated by Django 4.2.13 on 2026-08-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_loyaltytransaction_unique_award_per_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ['created_at']},
        ),
    ]
