# Generated by Django 4.2.13 on 2026-06-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_tenant__5f91fa_idx',
            old_name='appt_tenant_date_status_idx',
        ),
    ]
