# Generated by Django 4.2.13 on 2026-06-21 14:49

import bizal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='providers/', validators=[bizal.validators.validate_image_type]),
        ),
    ]
