# Generated by Django 4.2.13 on 2026-07-08 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffmember_role'),
        ('appointments', '0006_appointment_reminder_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_provider_profiles', to='staff.staffmember'),
        ),
    ]
