# Generated by Django 4.2.13 on 2026-06-21 14:49

import bizal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, upload_to='storefront/hero/', validators=[bizal.validators.validate_image_type]),
        ),
    ]
