# Generated by Django 4.2.13 on 2026-07-03 19:10

import bizal.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_background_color_tenant_text_color'),
        ('storefront', '0002_sync_image_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('text', 'Tekst'), ('image', 'Imazh'), ('cta', 'Thirrje për Veprim (CTA)'), ('gallery', 'Galeri Imazhesh'), ('features', 'Veçori / Shërbime'), ('testimonial', 'Dëshmi Klienti'), ('spacer', 'Hapësirë')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='storefront/sections/', validators=[bizal.validators.validate_image_type])),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('background_color', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
