# Generated by Django 4.2.13 on 2026-07-04 15:43

import bizal.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_nav_config'),
        ('storefront', '0004_delete_storefrontsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_key', models.CharField(max_length=40)),
                ('lock_key', models.CharField(blank=True, max_length=40)),
                ('section_type', models.CharField(choices=[('locked', 'Përmbajtje Origjinale'), ('text', 'Tekst'), ('image', 'Imazh'), ('cta', 'Thirrje për Veprim (CTA)'), ('gallery', 'Galeri Imazhesh'), ('spacer', 'Hapësirë')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='storefront/sections/', validators=[bizal.validators.validate_image_type])),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['page_key', 'order'],
            },
        ),
    ]
