# Generated by Django 4.2.13 on 2026-06-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_merge'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_tenant__a7e75e_idx',
            old_name='analytics_tenant_evtype_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_tenant__01398a_idx',
            old_name='analytics_tenant_created_idx',
        ),
    ]
