# Generated by Django 4.2.13 on 2026-08-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media'), ('walk_in', 'Walk-in'), ('call', 'Phone Call'), ('chatbot', 'Chatbot'), ('other', 'Other')], default='website', max_length=30),
        ),
    ]