# Generated by Django 4.2.13 on 2026-08-27 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0019_main_sentinel_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsabilitySurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('business_type_snapshot', models.CharField(blank=True, max_length=50)),
                ('familiar_with_bizal', models.BooleanField(blank=True, help_text='A e njihte BizAL-in më parë pjesëmarrësi?', null=True)),
                ('q1', models.PositiveSmallIntegerField(help_text='Pyetja 1 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q2', models.PositiveSmallIntegerField(help_text='Pyetja 2 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q3', models.PositiveSmallIntegerField(help_text='Pyetja 3 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q4', models.PositiveSmallIntegerField(help_text='Pyetja 4 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q5', models.PositiveSmallIntegerField(help_text='Pyetja 5 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q6', models.PositiveSmallIntegerField(help_text='Pyetja 6 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q7', models.PositiveSmallIntegerField(help_text='Pyetja 7 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q8', models.PositiveSmallIntegerField(help_text='Pyetja 8 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q9', models.PositiveSmallIntegerField(help_text='Pyetja 9 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q10', models.PositiveSmallIntegerField(help_text='Pyetja 10 e SUS (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sus_score', models.FloatField(blank=True, editable=False, null=True)),
                ('onboarding_duration_seconds', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Komente të lira, opsionale (citate cilësore për Kapitullin 4).')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usability_survey_responses', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
