# Generated by Django 4.2.13 on 2026-08-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Kur është aktiv, sondazhi SUS shfaqet pas çdo regjistrimi të ri.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurimi i sondazhit',
                'verbose_name_plural': 'Konfigurimi i sondazhit',
            },
        ),
    ]
