# Generated by Django 4.2.13 on 2026-06-03 08:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rental_type', models.CharField(choices=[('car', 'Car'), ('property', 'Property'), ('equipment', 'Equipment'), ('boat', 'Boat')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rentals/')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('is_featured', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
