# Generated by Django 4.2.13 on 2026-06-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenantlocation_id_alter_tenantreferral_id'),
        ('blog', '0003_blog_tenant_non_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
