# Generated by Django 4.2.13 on 2026-06-21 14:49

import bizal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogtag_options_alter_blogpost_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/', validators=[bizal.validators.validate_image_type]),
        ),
    ]
