# Generated by Django 4.2.13 on 2026-06-21 14:49

import bizal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[bizal.validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[bizal.validators.validate_image_type]),
        ),
    ]
