# Generated by Django 4.2.13 on 2026-06-21 14:49

import bizal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_roomtype_options_alter_seasonalprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/rooms/', validators=[bizal.validators.validate_image_type]),
        ),
    ]
