# Generated by Django 4.2.13 on 2026-08-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_sync_image_validators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roombooking',
            options={'ordering': ['-id']},
        ),
    ]
