# Generated by Django 4.2.13 on 2026-06-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='processed', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
