# Generated by Django 4.2.13 on 2026-06-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_unique_tenant_payment_intent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_stripe_session_id_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
