# Generated by Django 4.2.13 on 2026-07-08 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_reminder_attempts'),
        ('payments', '0006_remove_payment_payments_stripe_session_id_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.booking'),
        ),
    ]
