# Generated by Django 4.2.13 on 2026-06-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
